"""工具层依赖的协议端口，不暴露 SDK 对象。"""
from typing import Protocol
from app.domain.models.tool_result import ToolResult


class MCPGateway(Protocol):
    async def initialize(self) -> None: ...
    async def cleanup(self) -> None: ...
    async def get_all_tools(self) -> list[dict]: ...
    async def invoke(self, name: str, arguments: dict) -> ToolResult: ...


class A2AGateway(Protocol):
    @property
    def cards(self) -> list[dict]: ...
    async def initialize(self) -> None: ...
    async def cleanup(self) -> None: ...
    async def invoke(self, agent_id: str, query: str) -> ToolResult: ...
